import type { Metadata } from "next";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from "react-hot-toast"
import { ClerkProvider } from "@clerk/nextjs";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
          <Toaster
            position="top-center"
          />
          {children}
          {modal}
        </GoogleOAuthProvider>

      </body>
    </html>
  );
}
